### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by bixel** [pep-dortmund/corporate-design#1]
Super, dass wir das jetzt hier haben :+1: 
Ich finde das Spacing im "e.V." irgendwie komisch. Wie wäre es hiermit? :eyes: e1df04c
![bildschirmfoto 2016-02-18 um 10 46 28](https://cloud.githubusercontent.com/assets/2527718/13139450/f0efd186-d62c-11e5-8b1e-601a06fe5562.png)
zum Vergleich noch mal:
![bildschirmfoto 2016-02-18 um 10 47 47](https://cloud.githubusercontent.com/assets/2527718/13139483/15e1dc00-d62d-11e5-8c76-e1ef8812390f.png)

**Comment by maxnoe** [comment]
Besser
