### ISSUE TITLE
Requirements wären hilfreich

### ISSUE THREAD

**Issue by bixel** [pep-dortmund/corporate-design#5]
Beim `make` fehlt bei uns macOS-Usern `pdftoppm`. Ist das ein nicht-Latex-Paket? Ne Requirements section wäre hilfreich :-)

**Comment by maxnoe** [comment]
kommt aus poppler, mac: `brew install poppler`

**Comment by maxnoe** [comment]
Aber ja, requirements sind ne gute sache
